nginx:
    image: nutsllc/toybox-nginx
    links:
        - php-fpm
        - mariadb
    ports:
        - 8080:80
    environment:
        - PHP_FPM_HOST=php-fpm:9000
    volumes_from:
        - data

php-fpm:
    image: nutsllc/toybox-php:7.2-fpm
    links:
        - mariadb
    volumes_from:
        - data

mariadb:
    image: nutsllc/toybox-mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=root

data:
    image: busybox
    volumes:
        - "./data/application:/usr/share/nginx/html"
        - "./data/application:/application"
        - "./data/mariadb-conf:/var/run/mysql"
